// <auto-generated />
namespace ComplainMSModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changecolumntype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecolumntype));
        
        string IMigrationMetadata.Id
        {
            get { return "202008121338388_change column type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
